/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.GPB.frame;

import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFrame;

/**
 *
 * @author anouer
 */
public class AcceuilGui extends javax.swing.JFrame {

    public static String t3;
    private static ChartFrame frame;
    Connection connAccueil = null;
    ResultSet rs = null;
    PreparedStatement ps = null;

    /**
     * Creates new form AcceuilGui
     */
    public AcceuilGui() throws SQLException {
        initComponents();
        
        if(LoginGUI.role.equals("USER")){
            Utilisateur.setVisible(false);
        }
        //this.setIconImage(new ImageIcon(getClass().getResource("logocar.png")).getImage());
        connAccueil = ConexionBD.Conexion();
        recuperutlisateur();
        ActionEvent evt = null;
        JournalActionPerformed(evt);
        
//        Article.setBackground(new java.awt.Color(153, 153, 153));
//        Section.setBackground(new java.awt.Color(153, 153, 153));
//        Entree.setBackground(new java.awt.Color(153, 153, 153));
//        Fournisseur.setBackground(new java.awt.Color(153, 153, 153));
//        Sortie.setBackground(new java.awt.Color(153, 153, 153));
//        Journal.setBackground(new java.awt.Color(3, 91, 155));
//        Utilisateur.setBackground(new java.awt.Color(153, 153, 153));
        
        Journal.setBorderPainted(true);
        Article.setBorderPainted(false);
        Section.setBorderPainted(false);
        Entree.setBorderPainted(false);
        Fournisseur.setBorderPainted(false);
        Sortie.setBorderPainted(false);
        
        if(LoginGUI.role.equals("ADMIN")){
            Utilisateur.setBorderPainted(false);
        }
    }

    

    private void recuperutlisateur() {
        LoginGUI lo = new LoginGUI();

        try {
            String recp = lo.utilisateur();
            String requet = "select * from login_table where login = '" + recp + "'";
            ps = connAccueil.prepareStatement(requet);
            rs = ps.executeQuery();
            if (rs.next()) {
                String t2 = rs.getString("login");
//                lprenom.setText(t2);
                String t1 = rs.getString("login");
                lnom.setText(t1 + " " + t2);
                ps.close();
                rs.close();
            }
        } catch (SQLException e) {
            System.out.println(e);
        } finally {

            try {
                ps.close();
                rs.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }
    }

    public String utilisateurs() {
        return t3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logomax = new javax.swing.JLabel();
        menublanc = new javax.swing.JLabel();
        desk = new javax.swing.JDesktopPane();
        type = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lnom = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Utilisateur = new javax.swing.JButton();
        Journal = new javax.swing.JButton();
        Section = new javax.swing.JButton();
        Article = new javax.swing.JButton();
        Entree = new javax.swing.JButton();
        Fournisseur = new javax.swing.JButton();
        Sortie = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Appli_Gestion_de_stock_ACEEM");
        setMinimumSize(new java.awt.Dimension(1024, 380));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        logomax.setFont(new java.awt.Font("Armalite Rifle", 1, 24)); // NOI18N
        logomax.setForeground(new java.awt.Color(3, 91, 155));
        logomax.setText("Gestion de Stock Aceem");
        getContentPane().add(logomax);
        logomax.setBounds(10, 0, 610, 30);

        menublanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GPB/images/menu.png"))); // NOI18N
        getContentPane().add(menublanc);
        menublanc.setBounds(0, 0, 1370, 30);

        desk.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        getContentPane().add(desk);
        desk.setBounds(170, 40, 1190, 670);

        type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(type);
        type.setBounds(520, 70, 140, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(":");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(660, 70, 10, 17);

        lnom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lnom.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lnom);
        lnom.setBounds(670, 70, 320, 20);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        Utilisateur.setFont(new java.awt.Font("Bebas Neue Bold", 1, 18)); // NOI18N
        Utilisateur.setForeground(new java.awt.Color(3, 91, 155));
        Utilisateur.setText("Utilisateurs");
        Utilisateur.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(3, 91, 155)));
        Utilisateur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Utilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                UtilisateurMouseReleased(evt);
            }
        });
        Utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilisateurActionPerformed(evt);
            }
        });

        Journal.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        Journal.setForeground(new java.awt.Color(3, 91, 155));
        Journal.setText("Journal");
        Journal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(3, 91, 155)));
        Journal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Journal.setOpaque(false);
        Journal.setVerifyInputWhenFocusTarget(false);
        Journal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JournalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JournalMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JournalMouseReleased(evt);
            }
        });
        Journal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JournalActionPerformed(evt);
            }
        });

        Section.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        Section.setForeground(new java.awt.Color(3, 91, 155));
        Section.setText("Section");
        Section.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(3, 91, 155)));
        Section.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Section.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SectionMouseReleased(evt);
            }
        });
        Section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionActionPerformed(evt);
            }
        });

        Article.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        Article.setForeground(new java.awt.Color(3, 91, 155));
        Article.setText("Article");
        Article.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(3, 91, 155)));
        Article.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Article.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ArticleMouseReleased(evt);
            }
        });
        Article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticleActionPerformed(evt);
            }
        });

        Entree.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        Entree.setForeground(new java.awt.Color(3, 91, 155));
        Entree.setText("Entrée");
        Entree.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(3, 91, 155)));
        Entree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Entree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EntreeMouseReleased(evt);
            }
        });
        Entree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntreeActionPerformed(evt);
            }
        });

        Fournisseur.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        Fournisseur.setForeground(new java.awt.Color(3, 91, 155));
        Fournisseur.setText("Fournisseur");
        Fournisseur.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(3, 91, 155)));
        Fournisseur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Fournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FournisseurMouseReleased(evt);
            }
        });
        Fournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FournisseurActionPerformed(evt);
            }
        });

        Sortie.setFont(new java.awt.Font("Bebas Neue Bold", 0, 18)); // NOI18N
        Sortie.setForeground(new java.awt.Color(3, 91, 155));
        Sortie.setText("Sortie");
        Sortie.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(3, 91, 155)));
        Sortie.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Sortie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SortieMouseReleased(evt);
            }
        });
        Sortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortieActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(Utilisateur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Journal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Section, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Article, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Entree, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Fournisseur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Sortie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Article, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entree, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Journal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sortie, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Journal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Article, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sortie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(10, 110, 170, 570);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/GPB/images/logo2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 140, 70);

        setSize(new java.awt.Dimension(1382, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JournalActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Journal lc = null;
        try {
            lc = new Journal();
        } catch (SQLException ex) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.desk.add(lc);
        try {
            lc.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        lc.show();
    }//GEN-LAST:event_JournalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void SectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Section ex = null;
        try {
            ex = new Section();
        } catch (SQLException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_SectionActionPerformed

    private void UtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilisateurActionPerformed
        try {                                            
            this.desk.removeAll();
            this.desk.repaint();
            
            Utilisateur ex = new Utilisateur();
            this.desk.add(ex);
            try {
                ex.setMaximum(true);
            } catch (PropertyVetoException ex1) {
                Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
            }
            ex.show();
        } catch (SQLException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_UtilisateurActionPerformed

    private void JournalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JournalMouseReleased
        Journal.setBorderPainted(true);
        Article.setBorderPainted(false);
        Section.setBorderPainted(false);
        Entree.setBorderPainted(false);
        Fournisseur.setBorderPainted(false);
        Sortie.setBorderPainted(false);
        if(LoginGUI.role.equals("ADMIN")){
            Utilisateur.setBorderPainted(false);
        }
        
    }//GEN-LAST:event_JournalMouseReleased

    private void JournalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JournalMouseEntered
//     candidatbtn.setBackground(new java.awt.Color(51,2,255));
        
    }//GEN-LAST:event_JournalMouseEntered

    private void JournalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JournalMouseExited
//        candidatbtn.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_JournalMouseExited

    private void SectionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SectionMouseReleased
        Journal.setBorderPainted(false);
        Article.setBorderPainted(false);
        Section.setBorderPainted(true);
        Entree.setBorderPainted(false);
        Fournisseur.setBorderPainted(false);
        Sortie.setBorderPainted(false);
        if(LoginGUI.role.equals("ADMIN")){
            Utilisateur.setBorderPainted(false);
        }
    }//GEN-LAST:event_SectionMouseReleased

    private void UtilisateurMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UtilisateurMouseReleased
        Journal.setBorderPainted(false);
        Article.setBorderPainted(false);
        Section.setBorderPainted(false);
        Entree.setBorderPainted(false);
        Fournisseur.setBorderPainted(false);
        Sortie.setBorderPainted(false);
        Utilisateur.setBorderPainted(true);
    }//GEN-LAST:event_UtilisateurMouseReleased

    private void ArticleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArticleMouseReleased
        Journal.setBorderPainted(false);
        Article.setBorderPainted(true);
        Section.setBorderPainted(false);
        Entree.setBorderPainted(false);
        Fournisseur.setBorderPainted(false);
        Sortie.setBorderPainted(false);
        if(LoginGUI.role.equals("ADMIN")){
            Utilisateur.setBorderPainted(false);
        }
    }//GEN-LAST:event_ArticleMouseReleased

    private void ArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticleActionPerformed
        try {                                        
            this.desk.removeAll();
            this.desk.repaint();
            
            Article ex = null;
            ex = new Article();
            this.desk.add(ex);
            try {
                ex.setMaximum(true);
            } catch (PropertyVetoException ex1) {
                Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
            }
            ex.show();
        } catch (SQLException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_ArticleActionPerformed

    private void EntreeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntreeMouseReleased
        Journal.setBorderPainted(false);
        Article.setBorderPainted(false);
        Section.setBorderPainted(false);
        Entree.setBorderPainted(true);
        Fournisseur.setBorderPainted(false);
        Sortie.setBorderPainted(false);
        if(LoginGUI.role.equals("ADMIN")){
            Utilisateur.setBorderPainted(false);
        }
    }//GEN-LAST:event_EntreeMouseReleased

    private void EntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntreeActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Entree ex = null;
        try {
            ex = new Entree();
        } catch (SQLException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_EntreeActionPerformed

    private void FournisseurMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FournisseurMouseReleased
        Journal.setBorderPainted(false);
        Article.setBorderPainted(false);
        Section.setBorderPainted(false);
        Entree.setBorderPainted(false);
        Fournisseur.setBorderPainted(true);
        Sortie.setBorderPainted(false);
        if(LoginGUI.role.equals("ADMIN")){
            Utilisateur.setBorderPainted(false);
        }
    }//GEN-LAST:event_FournisseurMouseReleased

    private void FournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FournisseurActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Fournisseur ex = null;
        try {
            ex = new Fournisseur();
        } catch (SQLException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_FournisseurActionPerformed

    private void SortieMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SortieMouseReleased
        Journal.setBorderPainted(false);
        Article.setBorderPainted(false);
        Section.setBorderPainted(false);
        Entree.setBorderPainted(false);
        Fournisseur.setBorderPainted(false);
        Sortie.setBorderPainted(true);
        if(LoginGUI.role.equals("ADMIN")){
            Utilisateur.setBorderPainted(false);
        }
    }//GEN-LAST:event_SortieMouseReleased

    private void SortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortieActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Sortie ex = null;
        try {
            ex = new Sortie();
        } catch (SQLException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();
    }//GEN-LAST:event_SortieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new AcceuilGui().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Article;
    private javax.swing.JButton Entree;
    private javax.swing.JButton Fournisseur;
    private javax.swing.JButton Journal;
    private javax.swing.JButton Section;
    private javax.swing.JButton Sortie;
    private javax.swing.JButton Utilisateur;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel logomax;
    private javax.swing.JLabel menublanc;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
